apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: starwarsapi-deployment
spec:
  selector:
    matchLabels:
      app: starwarsapi
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: starwarsapi
    spec:
      containers:
      - name: starwarsapi
        image: rgbrunello/starwarsapi:0.1
        ports:
        - containerPort: 9000
